name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: LogVariables
      run: make print
    - name: LogStepsTest
      run: make -n test
    - name: LogStepsBuild
      run: make -n build
    - name: Test
      run: make clean test
    - name: Build
      run: make build
    - name: Confirm
      run: ./target/main.exe -v
